### ISSUE TITLE
any test  data available?

### ISSUE THREAD

**Issue by extr15** [damarquezg/rtslam#1]
hi, thanks for the great project at first. I want to test RT-SLAM and have already compiled OK. can you give me some test data as a start?
from this link:
https://www.openrobots.org/wiki/rtslam/Using
I get a link: http://homepages.laas.fr/croussil/videos/2011-02-15_inertial-high-dyn.zip
seems to be a sample image and IMU sequence, however it is dead.
can you help me? thanks so much!

**Comment by damarquezg** [comment]
you can find the latest release and the test data in this link: https://www.openrobots.org/wiki/rtslam/
